[package]
name = "tcp_file_send"
version = "0.1.0"
authors = ["fastAsF <pana.sonia@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
